#!/bin/bash
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
\curl -sSL https://get.rvm.io | bash -s stable
usermod -aG rvm vagrant
source /etc/profile.d/rvm.sh
rvm install 1.8.6
rvm --default use 1.8.6
gem install rake --include-dependencies -v 0.8.1
gem install rails --include-dependencies -v 2.1.1
